apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - name: frontend
        image: 995140118849.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
      restartPolicy: Always
